import type { Metadata } from 'next'
import { prisma } from '@/lib/db/prisma'

export const metadata: Metadata = {
  title: 'Terms of Service | ArguFight',
  description: 'Terms of Service for ArguFight.',
}

async function getPage() {
  try {
    return await prisma.legalPage.findUnique({ where: { slug: 'terms-of-service' } })
      ?? await prisma.legalPage.findUnique({ where: { slug: 'terms' } })
  } catch {
    return null
  }
}

export default async function TermsPage() {
  const page = await getPage()

  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <div className="mb-10">
        <p className="text-[13px] font-[500] text-accent uppercase tracking-widest mb-4">Legal</p>
        <h1 className="text-[40px] font-[700] tracking-[-1.5px] text-text mb-3">
          {page?.title ?? 'Terms of Service'}
        </h1>
        <p className="text-[14px] text-text-3">Last updated: March 2026</p>
      </div>

      <div className="h-px bg-border mb-10" />

      {page?.content ? (
        <div
          className="prose prose-sm max-w-none prose-headings:text-text prose-headings:font-[600] prose-headings:tracking-[-0.3px] prose-p:text-text-2 prose-p:leading-relaxed prose-strong:text-text prose-ul:text-text-2 prose-ol:text-text-2 prose-li:text-text-2 prose-a:text-accent prose-a:no-underline hover:prose-a:underline prose-hr:border-border"
          dangerouslySetInnerHTML={{ __html: page.content }}
        />
      ) : (
        <div className="prose prose-sm max-w-none text-text-2 space-y-8">

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">1. Acceptance of Terms</h2>
            <p className="text-[15px] leading-relaxed">
              By accessing or using ArguFight (&quot;the Platform&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">2. Use of the Platform</h2>
            <p className="text-[15px] leading-relaxed mb-3">
              You must be at least 13 years old to use ArguFight. By using the Platform, you represent that you meet
              this age requirement. You agree to use the Platform only for lawful purposes and in accordance with
              these Terms.
            </p>
            <p className="text-[15px] leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials and for all
              activities that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">3. Content and Conduct</h2>
            <p className="text-[15px] leading-relaxed mb-3">
              You are solely responsible for the content you submit on ArguFight. You agree not to post content that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-[15px] leading-relaxed text-text-3 ml-2">
              <li>Is unlawful, harmful, threatening, abusive, or harassing</li>
              <li>Infringes on any intellectual property rights</li>
              <li>Contains spam, malware, or unauthorized advertising</li>
              <li>Impersonates any person or entity</li>
              <li>Violates any applicable local, national, or international law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">4. Virtual Currency and Purchases</h2>
            <p className="text-[15px] leading-relaxed">
              ArguFight may offer virtual currency (&quot;Coins&quot;) and premium subscriptions. All purchases are
              final and non-refundable unless required by applicable law. Virtual currency has no real-world
              monetary value and cannot be exchanged for cash.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">5. AI-Generated Verdicts</h2>
            <p className="text-[15px] leading-relaxed">
              Debate verdicts are generated by AI systems and are provided for entertainment and skill-building
              purposes. ArguFight makes no warranty that AI verdicts are accurate, unbiased, or suitable for
              any particular purpose. Verdicts are final and not subject to appeal.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">6. Termination</h2>
            <p className="text-[15px] leading-relaxed">
              ArguFight reserves the right to suspend or terminate your account at any time, with or without
              notice, for conduct that we determine violates these Terms or is otherwise harmful to other
              users, the Platform, or third parties.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">7. Disclaimer of Warranties</h2>
            <p className="text-[15px] leading-relaxed">
              The Platform is provided &quot;as is&quot; without warranty of any kind. ArguFight disclaims all
              warranties, express or implied, including merchantability, fitness for a particular purpose,
              and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">8. Limitation of Liability</h2>
            <p className="text-[15px] leading-relaxed">
              To the maximum extent permitted by law, ArguFight shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages resulting from your use of or inability
              to use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">9. Changes to Terms</h2>
            <p className="text-[15px] leading-relaxed">
              We may update these Terms at any time. Continued use of the Platform after changes constitutes
              your acceptance of the revised Terms. We will notify users of material changes via email or
              in-platform notification.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-[600] text-text mb-3">10. Contact</h2>
            <p className="text-[15px] leading-relaxed">
              For questions about these Terms, contact us at{' '}
              <a href="mailto:info@argufight.com" className="text-accent hover:underline">
                info@argufight.com
              </a>.
            </p>
          </section>

        </div>
      )}
    </div>
  )
}
